//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm.virginactive.web.layouts.virginactive {
    
    
    public partial class PrimaryNavigation {
        
        /// <summary>
        /// FacilityClassNav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mm.virginactive.web.layouts.virginactive.navigation.FacilitiesClassesNav FacilityClassNav;
        
        /// <summary>
        /// YourHealth control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mm.virginactive.web.layouts.virginactive.navigation.YourHealthNav YourHealth;
        
        /// <summary>
        /// MemberNav control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mm.virginactive.web.layouts.virginactive.navigation.MembershipsNav MemberNav;
    }
}
