//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace mm.virginactive.web.layouts.virginactive.navigation {
    
    
    public partial class YourHealthNav {
        
        /// <summary>
        /// HealthArticles control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mm.virginactive.web.layouts.virginactive.navigation.NavLinkSection HealthArticles;
        
        /// <summary>
        /// HealthTools control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::mm.virginactive.web.layouts.virginactive.navigation.NavLinkSection HealthTools;
        
        /// <summary>
        /// BlogPostList control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.ListView BlogPostList;
    }
}
